root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = ["run", "--port", ":6116", "--log_level", "debug"]
  bin = "build/bin/lisfun_dev_darwin_arm64"
  cmd = "make"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "tools", "node_modules", "internal/models"]
  exclude_file = []
  exclude_regex = ["_test.go", "_templ.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html", "yml", "templ"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = ["pkill lisfun"]
  pre_cmd = ["pkill lisfun || true"]
  rerun = false
  rerun_delay = 1000
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = true

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
