version: 3
workdir: internal
excludeFiles: ["internal/db/*", ".*_test.go"]
allow:
  depOnAnyVendor: true
components:
  services:
    in: services/*

  views:
    in: app/views/**

  controllers:
    in: app/controllers/*

  app_contexts:
    in: app/context

  app_errors:
    in: app/errors

  app:
    in: app

  models:
    in:
    - app/models
    - services/models

  db:
    in:
    - db/**

  types:
    in:
    - types/**

  tests:
    in:
    - tests/**

commonComponents:
- models
- tests
- types
- tests

deps:
  tests:
    mayDependOn:
    - db

  models:
    mayDependOn:
      - db

  services:
    mayDependOn:
    - db
    - types
    - services

  views:
    mayDependOn:
    - app_contexts
    - views

  controllers:
    mayDependOn:
    - app_contexts
    - app_errors
    - views

  app_contexts:
    mayDependOn:
      - services
      - app_errors

  app:
    mayDependOn:
      - db
      - views
      - app_contexts
      - app_errors
      - controllers
      - services
