version: 3
workdir: internal
allow:
  depOnAnyVendor: true
components:
  service:
    in: services/*

  view:
    in: app/views/**

  controller:
    in: app/controllers/*

  app_context:
    in: app/context

  app_errors:
    in: app/errors

  app:
    in: app

  model:
    in:
    - models

deps:
  view:
    mayDependOn:
    - app_context
    - view

  controller:
    mayDependOn:
    - app_context
    - app_errors
    - view

  app_context:
    mayDependOn:
      - service
      - app_errors

  app:
    mayDependOn:
      - view
      - app_context
      - app_errors
      - controller
