version: 3
workdir: internal
allow:
  depOnAnyVendor: true
components:
  service:
    in: services/*

  view:
    in: app/views/**

  controller:
    in: app/controllers/*

  app_common:
    in: app/common

  app:
    in: app

  model:
    in:
    - models

deps:
  view:
    mayDependOn:
    - app_common
    - view

  controller:
    mayDependOn:
    - app_common
    - view

  app_common:
    mayDependOn:
      - service

  app:
    mayDependOn:
      - view
      - app_common
      - controller
